### ISSUE TITLE
Slow key generation

### ISSUE THREAD

**Issue by bibz0r** [neocogent/misc#1]
I'm running this on a virtual machine and trying to convert a few hundred strings but it is very slow. I can convert about maximum 5 strings/sec.

Is the bottleneck the environment? The VM is running from a HDD and has assigned 8GB RAM on a i3 Coffee Lake.. 

Or is this something completely normal? I guess maybe the needed randomness might be a delay?

**Comment by neocogent** [comment]
I don't know which script you're running. I can try it here and see how it compares. I have rngtools installed which adds entropy to /dev/random and that may make a big difference in some cases. I have a bunch of scripts in this repo and so not sure which one you're trying. I doubt hd or memory have any effect though.

**Comment by bibz0r** [comment]
Oh darn, sorry I forgot this repo is "misc".. I was running keyfmt. After trying to remove any possible bottlenecks and even after running my linux in a ramfs I wasn't able to get it quick enough so I gave up.

Apparently, from what I've found out googling, it seems like bitcoins eliptic curve is quite slow, especially with python's hashlib. Some people suggested trying to hack vanitygen so it produces addresses from strings. My intention was to convert a big amount of brain-wallets (quickly) to bitcoin addresses.

So therefor I guss this issue can be closed? Or do you have any other ideas other than this? Maybe my informations are wrong, so if you have any ideas and the time, I'd be glad for some help or pointing me in the right direction.

**Comment by neocogent** [comment]
There is a python wrapper for libsecp256k which would be much faster for EC math and I'd suggest using that. I didn't write this with the idea it would be fast or useful for bulk conversions. You could use this code and adjust it to work with libsecp256k (fast C library) using the python wrapper and it should be very fast. I think hashlib is fast but there may be other options that are much faster.

**Comment by bibz0r** [comment]
I guess this issue can be closed then. I will someday fork this repo and try implementing the libsecp256k wrapper. If I succeed I'll make a pull request 

Have a good day and thanks again for your script collection :)
